# -*- coding: utf-8 -*-
"""data_visualization_Sales.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1W9CAGluvFPfpBaLe4SZMfN7KuiLdCk6z
"""

import pandas as pd
import matplotlib.pyplot as plt

# Load the data from the CSV file
data = pd.read_csv('/content/sales.csv')

# Plot 1: Line plot of sales over time
plt.plot(data['Date'], data['Sales'])
plt.title('Sales over time')
plt.xlabel('Date')
plt.ylabel('Sales')
plt.show()

# Plot 2: Bar chart of total profit by year
data['Year'] = pd.to_datetime(data['Date']).dt.year
profit_by_year = data.groupby('Year')['Profit'].sum()
plt.bar(profit_by_year.index, profit_by_year.values)
plt.title('Total profit by year')
plt.xlabel('Year')
plt.ylabel('Profit')
plt.legend(['Profit'])
plt.show()

# Plot 3: Scatter plot of sales vs. profit
plt.scatter(data['Sales'], data['Profit'])
plt.title('Sales vs. Profit')
plt.xlabel('Sales')
plt.ylabel('Profit')
plt.legend(['Sales vs. Profit'])
plt.show()

# Plot 2: Bar chart of total profit by year
data['Year'] = pd.to_datetime(data['Date']).dt.year
profit_by_year = data.groupby('Year')['Profit'].sum()
plt.bar(profit_by_year.index, profit_by_year.values)
plt.title('Total Sales by year')
plt.xlabel('Year')
plt.ylabel('Sales')
plt.legend(['Sales per Year'])
plt.show()